#!/usr/bin/env bash

# Abort on errors
set -e

# Where the .docker directory should go
TARGET="$(pwd)"

# Where to place the test.php and test-db.php files
PUBLIC_DIR="${1:-.}"

# Clone the repository to a temporary location
TMP="$(mktemp -d)"
(cd "$TMP"; git clone "https://github.com/jdferreira/my-lemp" "$TMP")

# Copy the necessary files. This includes the full .docker directory, the
# test.php and test-db.php files, and the Makefile
cp -r "$TMP/.docker" "$TARGET/.docker"
cp "$TMP/test.php" "$TMP/test-db.php" "$PUBLIC_DIR"

# If the project already has a Makefile, do not replace it, but append the
# docker recipes to it
if [ -f "$TARGET/Makefile" ]; then
    (echo; cat "$TMP/Makefile.appendable") >> "$TARGET/Makefile"
else
    cp "$TMP/Makefile" "$TARGET"
fi

# Create an SSH key
ssh-keygen -t rsa -b 4096 -f .docker/workspace/.ssh/id_rsa -N secret

# Create the .docker/.env file
make docker-init
