version: '3.7'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password

  php-fpm:
    build:
      context: .
      dockerfile: php-fpm/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
        - HOST_USER_ID=${HOST_USER_ID}
        - HOST_GROUP_ID=${HOST_GROUP_ID}
        - TZ=${TZ}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "${HOST_APP_PATH}:/var/www/html"
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        - HOST_USER_ID=${HOST_USER_ID}
        - HOST_GROUP_ID=${HOST_GROUP_ID}
        - TZ=${TZ}
    volumes:
      - "${HOST_APP_PATH}:/var/www/html"
    ports:
      - "${HOST_HTTP_PORT}:80"
      - "${HOST_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
      - db

  workspace:
    build:
      context: .
      dockerfile: workspace/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
        - HOST_USER_ID=${HOST_USER_ID}
        - HOST_GROUP_ID=${HOST_GROUP_ID}
        - TZ=${TZ}
    volumes:
      - "${HOST_APP_PATH}:/var/www/html"
    ports:
      - "22:22"
